templates/CRM/Volunteer/Form/Manage/Define.tpl

Smarty doesn't replace line breaks with a space (as you'd expect in regular HTML), so I put the copy on one line intentionally. I think the text should have been on one line anyway for compatibility with the translation code parser.

VOL-47: Fixed whitespace issues in UI.

---

js/apps/define/define_controller.js
js/apps/define/define_views.js

External code can listen for the dialogclose event then access the list of updated needs.

Added extension point for define needs UI.

---

ang/volunteer.css

This had the effect of removing titles from all angular pages (but only on certain drupal themes)
e.g. http://dmaster.demo.civicrm.org/civicrm/a/#/status
There's actually a new angular directive in 4.7 which allows you to set the page title, which IMO is better than hiding it:
https://github.com/civicrm/civicrm-core/blob/master/ang/crmUi.js#L985

Remove drupal-only css hack

---

CRM/Volunteer/Form/VolunteerSignUp.php

The resulting behavior was that additional volunteers (aka group registrations) could sign up to any
volunteer project, even if the profiles were configured to allow individual sign-up only.

Fixed regression resulting from the decision to store profile module_data as JSON.

---

CRM/Volunteer/Form/Commendation.php
CRM/Volunteer/Form/Log.php
CRM/Volunteer/Form/VolunteerSignUp.php
CRM/Volunteer/Permission.php
xml/Menu/Volunteer.xml

Could @TobiasLounsbury or @ginkgomzd review this, please?
Thinking about this some more, I wonder if I didn't go far enough. Perhaps we should skip checking perms at the menu entry level altogether and do like we do for [the public sign up form](https://github.com/civicrm/org.civicrm.volunteer/blob/v4.6-2.0.beta2/CRM/Volunteer/Form/VolunteerSignUp.php#L132-L138).
Benefits:
* We can use CRM_Volunteer_Permission::checkProjectPerms() to ensure the user has permission to access this particular log.
* Consistency with regard to how we deal with Joomla instances' poor handling of extension-based permissions.
Quack, quack.

Replace menu-level access control with fine-grained context-aware access control

---

js/backbone/apps/assign/assign_views.js

Sidestepped race condition by deferring DOM lookup until menuItemTemplate() is called.

VOL-175: Fixed rendering of menus for moving/copying volunteers on the Assign UI.

---

CRM/Volunteer/BAO/Project.php

If a volunteer project is associated with an event and the event is later deleted,
CiviVolunteer will log this instead of allow the application to crash and burn when
details are requested about the associated entity.

Log fact that associated entity is missing rather than allow the app to crash.

---

api/v3/VolunteerUtil.php

Reverts civicrm/org.civicrm.volunteer#374. This code misinterprets the meaning of an empty countryLimit list, which is to be interpreted as all countries rather than no countries.
---
* [VOL-208: Better handling when instance has no available countries](https://issues.civicrm.org/jira/browse/VOL-208)

Revert "VOL-208: Added checks to make sure Country.get API does not fail."

---

CRM/Volunteer/BAO/Project.php
CRM/Volunteer/Form/Settings.php
api/v3/VolunteerUtil.php
settings/volunteer.setting.php
volunteer.slider.php

This PR also includes a fix for a minor bug in which the default value for a setting couldn't be read because it was formatted improperly. It's minor because:
- the setting in question still hasn't been part of a formal release
- user-provided values for the setting were being formatted properly and could be retrieved and used as expected

Migrate settings access from BAO to API

---

ang/volunteer/Project.html

* [VOL-224: When updating a project, changing the country field alone isn't enough to cue an update](https://issues.civicrm.org/jira/browse/VOL-224)

VOL-224: Fixed bug where changes to country field didn't suffice to make the loc block dirty.

---

ang/volunteer/Project.js

* [VOL-248: Regression: Custom project relationship fields are not displayed on project create\/edit screen](https://issues.civicrm.org/jira/browse/VOL-248)

VOL-248: Display custom project relationship fields on the project create/edit screen.

---

CRM/Volunteer/Form/VolunteerSignUp.php

In CiviVolunteer v1, admins could use Activity fields in profiles used during volunteer registration.
In v2, the volunteer registration form was made significantly more flexible and commensurately more complex. While profiles with Activity fields can still be specified and are indeed still displayed to the user, the user-submitted data is not saved... not without this patch, anyway.
---
* [VOL-249: Regression: Activity fields added via profile are not processed on volunteer registration](https://issues.civicrm.org/jira/browse/VOL-249)

Fix for VOL-249: Activity fields added via profile are not processed on volunteer registration

---

css/signup.css
js/CRM_Volunteer_Form_VolunteerSignUp.js
templates/CRM/Volunteer/Form/VolunteerSignUp.tpl

Based the fix on the code for the similar project description popup.
---
* [VOL-250: Role comment bubble broken on sign up page](https://issues.civicrm.org/jira/browse/VOL-250)

Fix for VOL-250: Role detail is broken.

---

CRM/Volunteer/Form/VolunteerSignUp.php

Fixed implicit assumption that there would *always* be Activity fields in the sign-up profiles.
---
* [VOL-249: Regression: Activity fields added via profile are not processed on volunteer registration](https://issues.civicrm.org/jira/browse/VOL-249)

More work on VOL-249.

---

CRM/Volunteer/Form/VolunteerReport.php

The Volunteer report displays a PHP warning:
> User warning: Type is not defined for field status_id in CRM_Report_Form->whereClause() (line 1830 of /home/wmortada/buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Report/Form.php).
I've fixed this by adding a type for the status_id field.
---
* [CRM-19498: PHP notice on Volunteer Report](https://issues.civicrm.org/jira/browse/CRM-19498)

CRM-19498 Fix PHP warning in Volunteer Report

---

CRM/Volunteer/BAO/Project.php
CRM/Volunteer/Permission.php
ang/volunteer/Project.js
api/v3/VolunteerProjectContact.php
phpunit.xml.dist
tests/phpunit/VolunteerTestAbstract.php
tests/phpunit/api/v3/VolunteerProjectTest.php
tests/phpunit/bootstrap.php

With these commits, the following manual user tests pass:
* create via API as admin with just a title, expect all defaults applied
* update via GUI as admin with new project contacts, expect only project contacts to change
* update via GUI as admin with new profiles, expect only profiles to change
* update via API as admin with new project contacts, expect only project contacts to change
* update via API as admin with new profiles, expect only profiles to change
* create via GUI as admin, expect defaults not to override supplied values
* create via API as coord with just a title, expect all defaults applied
* create via GUI as coord, expect project contact and profiles supplied
* update via GUI as coord, expect project contact and profiles unchanged
* update via API as coord, expect …

VOL-202: Bugfixes for newly implemented updates.

---

ang/volunteer/Projects.js

* [VOL-267: "Select all" checkbox for bulk operations is too greedy](https://issues.civicrm.org/jira/browse/VOL-267)

VOL-267: greedy bulk actions

---

ang/volunteer/Projects.html
ang/volunteer/Projects.js
api/v3/VolunteerProjectContact.php
api/v3/VolunteerUtil.php

* [VOL-276: Deprecate api.VolunteerUtil.getbeneficiaries](https://issues.civicrm.org/jira/browse/VOL-276)

VOL-276: Path to deprecating api.VolunteerUtil.getbeneficiaries.

---

CRM/Volunteer/Form/VolunteerReport.php

* [VOL-284: Use entityRef widgets for activity contact filters on the volunteer report](https://issues.civicrm.org/jira/browse/VOL-284)

VOL-284: Use entityRef widgets for activity contact filters on the volunteer report

---

CRM/Volunteer/Form/VolunteerSignUp.php

* [VOL-315: Correct implicit assumption that group registration profiles will always have activity fields](https://issues.civicrm.org/jira/browse/VOL-315)

VOL-315: Fixed implicit assumption that group registration profiles will *always* have Activity fields.

---

CRM/Volunteer/BAO/Project.php

Before this fix, visiting the "Manage events" page (when at least one event has an associated volunteer project, and the server is running PHP 7.1) would give the following error:
> Error: Cannot pass parameter 1 by reference in CRM_Volunteer_BAO_Project::retrieve() (line 478 of /home/sean/buildkit/build/ext/sites/default/files/civicrm/ext/org.civicrm.volunteer/CRM/Volunteer/BAO/Project.php).
This fix changes the call to `copyValues()` so that it passes a variable, making this code compatible with PHP 7.1 and above.
Here is a comparison of this behavior in different PHP versions: https://3v4l.org/b9Jea

Fix PHP 7.1 Error: Cannot pass parameter 1 by reference

---

ang/volunteer/Project.js
volunteer.php

See https://code.angularjs.org/1.5.11/docs/api/ng/service/$sce.

VOL-209: Prevents "Error: [$sce:unsafe] Attempting to use an unsafe value in a safe context" if admin-defined help text contains markup.

---

js/backbone/apps/volunteer_app.js

* [VOL-318: Breakage caused by use of Backbone.noConflict\(\) introduced in CiviCRM 4.7.31](https://issues.civicrm.org/jira/browse/VOL-318)

VOL-318: Addresses Backbone using CiviCRM's namespace.

---

CRM/Volunteer/Upgrader.php

This problem was encountered while upgrading a very out-of-date CiviVolunteer to current.
Without this patch, the upgrade path results in a schema with an autogenerated name for one of its foreign key constraints. In the install path, the same constraint is explicitly provided a name, making it easy to reference in later queries. Later upgrade queries assume the constraint has the name supplied by the installer and will fail if the assumption proves false.

Whether passing through upgrade path or install path, ensure consistent naming of foreign key constraint

---

ang/volunteer/VolOppsCtrl.html

fix variable-type prefixed in option, e.g. "string:4"
https://stackoverflow.com/questions/30120230/how-to-suppress-variable-type-within-value-attribute-using-ng-options#30292209

fix var-type prefix in select option

---

CRM/Volunteer/Permission.php

On a local demo site with CiviVolunteer (and with `error_reporting(E_ALL)`), anytime I clear the cache
(`/civicrm/clearcache`), it shows this warning:
This is because `CRM_Volunteer_Permission` extends `CRM_Core_Permission` and overrides `check()`, but the signature for upstream `check()` has changed to allow another argument.
I don't think the inheritance/override relationship here is functionally required -- as near as I can tell:
* Everything in `civicrm-core` which uses `CRM_Core_Permission` calls `CRM_Core_Permission` specifically. They would never substitute with an instance of `CRM_Volunteer_Permission`.
* Everything in `civivolunteer` which needs `CRM_Volunteer_Permission` calls `CRM_Volunteer_Permission`.
What purpose did the inheritance serve?  The idea seems to be this: …

Permission.php - Disinherit CRM_*_Permission. Fix warning.

---

api/v3/VolunteerUtil.php
js/backbone/apps/search/search_views.js

After upgrading to CiviCRM 5.4.1 we get the following error: 
**'Error in call to CustomField…_get : 'AdvMulti-Select' is not a valid option for field html_type'**
This PR fixes this error. This is caused by the fact that the AdvMulti-Select field is removed since CiviCRM 5.3

Fixed compatibility with civicrm > 5.3

---

volunteer.php

This makes the menu entry look nice.
Note: I couldn't think of a better icon than this. Even though it's already designated as signifying "groups" in civicrm I think it's ok to mean volunteers too.

Add icon to top level menu entry

---

CRM/Volunteer/Hook.php

Per https://github.com/civicrm/civicrm-core/pull/17995 this updates the hook invoke to the new way (since circa 2017)

Update hook signature

---

CRM/Volunteer/BAO/NeedSearch.php

If you search for 2020-11-19 - 2020-11-19, it should show
opportunities on 2020-11-19. With this patch it does, without
this patch it does not.

ensure searches are inclusive of end date

---

ang/volunteer/Project.html

Expose field “Address Name” in volunteer project location. This is in keeping with other location displays like contacts, events, etc.

Expose field “Address Name” in volunteer project location

---

templates/CRM/Volunteer/Page/Roster.tpl

The button doesn’t work but we don’t really need it is a popup window we can close by clicking on the X.

seems redundant and doesn't work anyway

---

ang/volunteer.ang.php
volunteer.php

Straightforward refactor moves module definition out of the hook function and into an `.ang.php` file.
Adds a code comment that `CRM.vars['org.civicrm.volunteer'].currentContactId` is deprecated.

REF - Move angular module definition to its own file and deprecated unused var

---

CRM/Volunteer/BAO/NeedSearch.php
CRM/Volunteer/BAO/Project.php
api/v3/VolunteerNeed.php
tests/phpunit/CRM/Volunteer/BAO/AssignmentTest.php
tests/phpunit/CRM/Volunteer/BAO/ProjectTest.php

Civi 5.60 removes `CRM_Core_OptionGroup::getValue()`. This updates the code to the non-deprecated equivalent.
Note that I didn't get every single one in the tests - I'm not convinced any of my clients are using this, so I put in the effort needed to make sure crashes didn't happen.

Replace deprecated CRM_Core_OptionGroup::getValue()

---

info.xml

@ginkgomzd @homotechsual - we really need to tag this to avoid a hard fail on a very old long deprecated function that was removed. I incremented the version to 5.60 since earlier Civi versions are 'ok' at least on this issue so incrementing the version is more conservative
There is another problem that persists even with this on saving events on the latest civi - but I would do a second release if we figure that out rather than delay getting this important fix out

Update info.xml - tag release cos this hard-fails on 5.60+ without a new release

---

volunteer.php

`_id` is now a private property of the `$page` object.  This accesses it via a getter instead of directly.

access private property via getter

---

CRM/Volunteer/Permission.php

As of CiviCRM 5.71, these warnings appear:
```
User deprecated function: Permission 'register to volunteer' should be declared with 'label' and 'description' keys. See https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_permission/ Caller: CRM_Core_Permission::assembleBasicPermissions in CRM_Core_Error::deprecatedWarning() (line 1129 of /var/www/html/vendor/civicrm/civicrm-core/CRM/Core/Error.php).
User deprecated function: Permission 'log own hours' should be declared with 'label' and 'description' keys. See https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_permission/ Caller: CRM_Core_Permission::assembleBasicPermissions in CRM_Core_Error::deprecatedWarning() (line 1129 of /var/www/html/vendor/civicrm/civicrm-core/CRM/Core/Error.php).
...
```
... along with similar …

Fix deprecation warnings for permissions array in 5.71

---

CRM/Volunteer/Page/Roster.php

I'm not sure if this code ever worked. The old code was running date_add on the start_time as a string instead of an object.
I re-organized the code a little to make it more readable.

Avoid errors when end_time is not specified

---

css/volunteer_events.css

When using the islands theme, the buttons to Define Volunteer, Opportunities Assign Volunteers, and Log Volunteer Hours on the event tab appear with a white background, which makes them hard to read. This css fix makes them  more visible.

ensure buttons have non-white background

---

templates/CRM/Volunteer/Page/Backbone/Define.tpl

When using smarty4, the "Define Volunteer Opportunities",  "Assign Volunteers", and "Log Volunteer Hours" buttons don't work because the Define.tpl smarty template fails to load.
The failure of the Smarty template is due to the syntax: 
```
{help id="volunteer-define" file="CRM/Volunteer/Page/Backbone/Define.hlp" isModulePermissionSupported=│projects[osdi-client][download][revision] = "422cd55498b2d888ee72364962e6a831da9a6796"
`$isModulePermissionSupported`} 
```
Backticks should be enclosed in double quotes. And also, they are only necessary if the variable has a period.

avoid template error with smarty4

---

CRM/Volunteer/Angular/Tab/Event.php
CRM/Volunteer/BAO/Assignment.php
CRM/Volunteer/BAO/Commendation.php
volunteer.php

Avoids:
```
Error: Access to undeclared static property CRM_Event_DAO_Event::$_tableName in CRM_Volunteer_Angular_Tab_Event::prepareTab() (line 36 of /var/www/powerbase/sites/all/extensions/civivolunteer/CRM/Volunteer/Angular/Tab/Event.php).
```

CiviCRM no longer has $_tableName property

---

CRM/Volunteer/Form/VolunteerSignUp.php
volunteer.php

As indicated in #577 this fix resolves incorrect generated `volunteer/signup` URLs that are generated as backend URLs rather than frontend ones.

org.civicrm.volunteer#577 Resolving incorrect backend url generation

---

volunteer.php

This hook signature is changing, and will not always be called with 'validate' context when this extension expects it to.
This is the minimal safe/compat fix.
See https://github.com/civicrm/civicrm-core/pull/30986

Update hook_civicrm_fieldOptions to handle other contexts
