civicrm/org.civicrm.volunteer

CRM/Volunteer/Form/Log.php
templates/CRM/Volunteer/Form/Log.tpl

There are a lot of whitespace changes in this patch; it's not as big as it looks. It might be easier to review this PR commit-by-commit or using the split rather than the unified view.

VOL-34: Fixes around validation and required fields.

---

js/commendation.js
templates/CRM/Volunteer/Form/Log.tpl
templates/CRM/Volunteer/Form/Volunteer.tpl

Some of the old classes stop working in 4.6. The new names work in both 4.5 and 4.6.

VOL-110: Updated classes for icons.

---

CRM/Volunteer/BAO/NeedSearch.php
CRM/Volunteer/BAO/Project.php
README.md
ang/volunteer.js
ang/volunteer/Project.html
ang/volunteer/Project.js
ang/volunteer/VolOppsCtrl.html
ang/volunteer/VolOppsCtrl.js
api/v3/VolunteerNeed.php
api/v3/VolunteerUtil.php
tests/phpunit/CRM/Volunteer/BAO/ProjectTest.php
tests/phpunit/api/v3/VolunteerNeedTest.php
volunteer.php

Primarily the point of this pull request is to port the vol opp search logic from JS to PHP, where we have more control over permissions and where things are generally a little easier to do.

Refactor search

---

ang/volunteer/Project.js

Fixing it restores the redirect-after-save functionality.

Fixed bad reference to ID of saved project.

---

CRM/Volunteer/BAO/Assignment.php
CRM/Volunteer/BAO/Project.php
tests/phpunit/CRM/Volunteer/BAO/AssignmentTest.php
tests/phpunit/CRM/Volunteer/BAO/ProjectTest.php

Based off of @JohnFF's work on #297.

VOL-154: Propagate Campaign Tag to Activities Associated with a Project

---

ang/volunteer/Project.html
ang/volunteer/Project.js

Addresses the problem by:
* removing the crmEntity widgets when they are harmful rather than helpful
* adding form validation to ensure that all the core project relationships are set

VOL-174: When creating new projects, users lacking access to view the default contacts for the project relationships can't submit the form.

---

ang/volunteer/Project.js

Select2 gives us strings, not arrays.

Fixed inescapable validation error.

---

api/v3/VolunteerUtil.php
js/backbone/entities/vol_custom_field.js

Could @TobiasLounsbury or @ginkgomzd take a look at this, please?

Port fetching of volunteer custom fields from JS to PHP.

---

CRM/Volunteer/Upgrader.php
volunteer.php

error messages for extension dependency, angularprofiles

fixes Vol 151

---

ang/volunteer/Project.html
ang/volunteer/Project.js

Country ID was misnamed and thus not saved.

Fixed bug in creating location blocks.

---

CRM/Volunteer/BAO/Project.php

Country ID to name conversion was not passed along to geocoder.

Fixed bug in proximity search.

---

js/backbone/apps/define/define_views.js
js/backbone/entities/needs.js

Define needs defaults

---

ang/volunteer/Projects.html
ang/volunteer/Projects.js

Corrected inconsistent references to the project's campaign property.

Fixed broken campaign filter on Manage Projects page.

---

CRM/Volunteer/Form/Volunteer.php
volunteer.php

FYI @TobiasLounsbury and @axon-obriend.

Event tab bugfixes

---

CRM/Volunteer/Upgrader.php

lower 's' was causing errors durin intallation

 s/Multi-static/Multi-Static/g 

---

CRM/Volunteer/Form/Defaults.php

* [VOL-200: Allow setting of default values on the Project Settings page](https://issues.civicrm.org/jira/browse/VOL-200)

VOL-200: Language update for consistency with other field.

---

CRM/Volunteer/Form/Settings.php
settings/volunteer.setting.php
templates/CRM/Volunteer/Form/Settings.tpl

This PR builds off of VOL-203: so it should not be merged until after 203 has been QA'd and merged.
---
* [VOL-203: Allow specification of which Campaigns are visible in Volunteer forms](https://issues.civicrm.org/jira/browse/VOL-203)

Vol 204 settings metadata

---

CRM/Volunteer/DAO/Need.php
CRM/Volunteer/DAO/Project.php
CRM/Volunteer/DAO/ProjectContact.php
api/v3/VolunteerNeed.php
xml/schema/Volunteer/Need.xml
xml/schema/Volunteer/Project.xml
xml/schema/Volunteer/ProjectContact.xml

* [VOL-196: API Basic Get ignores entity definition](https://issues.civicrm.org/jira/browse/VOL-196)

VOL-196: update schema metadata for compatibility with core API changes

---

api/v3/VolunteerUtil.php

* [VOL-208: Better handling when instance has no available countries](https://issues.civicrm.org/jira/browse/VOL-208)

VOL-208: Added checks to make sure Country.get API does not fail.

---

templates/CRM/Volunteer/Form/Manage/Define.tpl

* [VOL-207: Broken "delete" icon in Define Volunteer Opportunities UI](https://issues.civicrm.org/jira/browse/VOL-207)

VOL-207 Replace image with text for delete.

---

ang/volunteer.css
ang/volunteer/VolOppsCtrl.html
ang/volunteer/VolOppsCtrl.js

Includes all of the code contributed in #372 as well as some cleanup, refactoring, and styling.
---
* [VOL-206: Improve "Shopping Cart" on Opportunities screen](https://issues.civicrm.org/jira/browse/VOL-206)

VOL-206: Usability improvements to volunteer shopping cart

---

ang/volunteer/Project.html
ang/volunteer/Project.js

@TobiasLounsbury, I made this change so that the code that was previously triggered by locBlockChanged (namely setting of the default country), could be triggered were the location block ID to be changed before the form is rendered (i.e., by crmHook).

Refactor loc block changes

---

CRM/Volunteer/Form/VolunteerSignUp.php

* [VOL-246: Cannot register additional volunteers](https://issues.civicrm.org/jira/browse/VOL-246)

VOL-246: Supplied missing argument to createVolunteerActivity.

---

templates/CRM/Volunteer/Form/VolunteerSignUp.tpl

These are the same classes in use on the vol opps UI.

Added selectors to the summary table.

---

ang/volunteer/Projects.html
ang/volunteer/Projects.js

Added Manage Projects text to explain automatic filtering.

Varl 135 manage projects help text

---

CRM/Volunteer/Upgrader.php
CRM/Volunteer/Upgrader/Base.php
volunteer.civix.php
volunteer.php

* [VOL-264: Support new extension version storage\/access mechanism](https://issues.civicrm.org/jira/browse/VOL-264)

VOL-264: Upgraded civix.

---

CRM/Volunteer/BAO/Project.php
CRM/Volunteer/Form/Settings.php
api/v3/VolunteerProject.php
settings/volunteer.setting.php

* [VOL-202: Add Project Relationship Defaults to Defaults UI](https://issues.civicrm.org/jira/browse/VOL-202)

VOL-202: Minor refactoring, better doc, make all default settings act on API layer.

---

CRM/Volunteer/Upgrader.php

Avoids order of operation problems detailed in VOL-237.
---
* [VOL-237: Installer expects access to CiviVolunteer settings before they are available](https://issues.civicrm.org/jira/browse/VOL-237)

VOL-237: Moved code for setting default value for slider_widget_fields setting into the postInstall hook.

---

ang/volunteer/Project.js
api/v3/VolunteerProject.php

* [VOL-247: Creating a project with no location gives a fatal error](https://issues.civicrm.org/jira/browse/VOL-247)
* [VOL-251: Unable to add location to project](https://issues.civicrm.org/jira/browse/VOL-251)

Fix for location issues VOL-247 and VOL-251

---

ang/volunteer/Projects.js

* [VOL-268: Bulk operations fail following project deletion](https://issues.civicrm.org/jira/browse/VOL-268)

VOL-268: Fixed problem of deletes breaking further bulk operations.

---

CRM/Volunteer/BAO/Need.php
CRM/Volunteer/BAO/Project.php
ang/volunteer/Project.js

* [VOL-269: "Flexible" Need is not always created on Project create](https://issues.civicrm.org/jira/browse/VOL-269)

VOL-269: "Flexible" Need is not always created on Project create

---

CRM/Volunteer/Form/VolunteerSignUp.php
js/VolunteerSignUp.js
templates/CRM/Volunteer/Form/Error.tpl

* [VOL-282: Volunteers can register for filled opportunities](https://issues.civicrm.org/jira/browse/VOL-282)

VOL-282: Removed two avenues which allowed over-registration of volunteer opps

---

CRM/Volunteer/Form/VolunteerReport.php

* [VOL-285: Volunteer Reports Broken](https://issues.civicrm.org/jira/browse/VOL-285)

VOL-285: Backported method introduced to a parent class in 4.7, jammed it on our report class.

---

CRM/Volunteer/Form/Log.php
js/CRM_Volunteer_Form_Log.js
templates/CRM/Volunteer/Form/Log.tpl

* [VOL-283: Allow removal of entries from the project coordinator's Log Hours UI](https://issues.civicrm.org/jira/browse/VOL-283)

VOL-283: Allow removal of entries from the project coordinator's Log Hours UI

---

ang/volunteer.js

* [VOL-187: Error: "Beneficiary is not a valid integer" when searching by more than one beneficiary](https://issues.civicrm.org/jira/browse/VOL-187)

VOL-187: Fixes bug when searching by more than one beneficiary.

---

CRM/Volunteer/Form/Log.php
templates/CRM/Volunteer/Form/Log.tpl

* [VOL-289: Log Volunteer Hours form should use custom Date format](https://issues.civicrm.org/jira/browse/VOL-289)

VOL-289: Log Volunteer Hours form should use custom Date format

---

CRM/Volunteer/BAO/Project.php
managed/CustomFields.mgd.php

Added support for writing custom data to volunteer projects.
---
* [VOL-296: Custom fields for volunteer projects](https://issues.civicrm.org/jira/browse/VOL-296)

VOL-296: Registered Volunteer Project as an entity extensible via custom field.

---

CRM/Volunteer/BAO/Project.php
managed/CustomFields.mgd.php

Life is much improved if the values for cg_extend_objects optionValues match the related entity's name.

custom field fix

---

CRM/Volunteer/Form/VolunteerReport.php

* [VOL-305: Volunteer Report - Unknown extension key in a translation string: org.civicrm.volunteer.](https://issues.civicrm.org/jira/browse/VOL-305)

VOL-305: Correct extension domain for translation in Volunteer Report.

---

README.md
docs/index.md
info.xml
volunteer.php

- README: now can be much shorter since this content is in the docs
guide
- Update docs/index.md with some of the content from the README not
already captured
- Update docs URL in info.xml
- Update docs URL which gets presented to users after installing

Point several things to new documentation guide

---

js/checkResourceUrl.js
volunteer.php

* [VOL-314](https://issues.civicrm.org/jira/browse/VOL-314)

VOL-314: Remove resource URL check now that core has its own.

---

CRM/Volunteer/Form/Settings.php
ang/volunteer/Project.html
api/v3/VolunteerUtil.php
settings/volunteer.setting.php

- [VOL-209: Allow addition of user-controllable help text on Project Settings screen](https://issues.civicrm.org/jira/browse/VOL-209)

VOL-209: Allow addition of user-controllable help text on Project Settings screen

---

ang/volunteer/Projects.html

Adds a Public Signup link to each project on the manage volunteer projects page, like the Event Signup links found on the Manage Events page.

---

ang/volunteer.css
ang/volunteer/Project.html

- Added label to profile selector.
- Improved consistency with other form elements on this screen.
- Gave up trying to force the "Use For" elements onto the same line
as the profile selector, improving readability of the "Use For"
options.

Improved profile selection UI when creating projects.

---

CRM/Volunteer/BAO/Assignment.php

So one can access it from the API using the entity "VolunteerAssignment"

Added assignment contact id to BAO

---

templates/CRM/Volunteer/Page/Backbone/Assign.tpl

ping @ginkgomzd @universalhandle 
This improves the handling of the display_name field in your templates.

Improve handling of display_name field in templates

---

js/backbone/apps/assign/assign_views.js

fix scheduled time not set if set through drag and drop screen

fix scheduled time not set if set through drag and drop screen

---

CRM/Volunteer/BAO/Assignment.php

Set role ID when Volunteers are moved to Volunteer needed.

---

volunteer.php

Set Assigned to field by default on creating on Volunteer activity instead of With Contact field
---
* [VOL-313: Assign volunteer activity to the Volunteer \(TFC-93\)](https://issues.civicrm.org/jira/browse/VOL-313)

VOL-313: TFC-93 - Assign volunteer activity to the Volunteer

---

CRM/Volunteer/BAO/NeedSearch.php

Fix in sql query for Volunteer Opportunity.

VARL-338 : Fix one issue in sql query.

---

CRM/Volunteer/Form/VolunteerReport.php

#521 - save select clauses for later use

---

CRM/Volunteer/BAO/NeedSearch.php
CRM/Volunteer/BAO/Project.php
CRM/Volunteer/Form/VolunteerSignUp.php
api/v3/VolunteerUtil.php

Address PHP Notices

---

docs/projects.md

Line 11 - change from in page anchor

Broken link to Volunteer Opportunties

---

docs/projects.md

Correct spelling mistake

---

CRM/Volunteer/Upgrader/Base.php
volunteer.civix.php

ping @eileenmcnaughton @colemanw

Regenerate Civix Generated files

---

CRM/Volunteer/Angular.php
CRM/Volunteer/Form/VolunteerSignUp.php

Fix loading of jquery notify ui package in D8/D9 context

---

CRM/Volunteer/Upgrader.php

@ginkgomzd @MikeyMJCO @demeritcowboy
Another fix I missed from my earlier PR

Additional install fix

---

ang/volunteer/Project.html
ang/volunteer/VolOppsCtrl.html

Debug blocks don't really belong in production code.

Remove kitchen sink debug blocks

---

ang/volunteer/Project.html
ang/volunteer/Project.js

Overview
---------
Followup from #569 this completes the campaign cleanup and fixes the project edit form.
Before
----------
Fatal error when editing a volunteer project.
After
-------
Error fixed; campaign selector works.

Fix fatal error caused by incomplete campaign cleanup

---

CRM/Volunteer/BAO/Assignment.php

copy over duration to Volunteer activity

copy over duration to Volunteer activity

---

templates/CRM/Volunteer/Page/Roster.tpl

Before
----------
After
-------

changes to roster UI

---

templates/CRM/Volunteer/Page/Roster.tpl

Before
----------
No tracking of email sent.
After
-------
Since email has been sent via CiviCRM, Email activity is logged.

use civicrm email functionality to keep track of the interactions

---

CRM/Volunteer/BAO/Project.php
CRM/Volunteer/DAO/Project.php
CRM/Volunteer/Form/Settings.php
CRM/Volunteer/Page/Router.php
tests/phpunit/api/v3/VolunteerNeedTest.php
tests/phpunit/api/v3/VolunteerProjectContactTest.php
xml/schema/CRM/Volunteer/Project.xml

Just some autoformatting I did in core that happened to update this extension because it was in the same directory.
All good changes.

Random code cleanup ported from core

---

xml/auto_install.xml
xml/volunteer_interest_install.xml

Before: 
Attempt to install extension and get a mysterious DB Error. Extension Fails to install.
After: 
Attempt to install extension and get a different error - addressed in https://github.com/civicrm/org.civicrm.volunteer/pull/617
Note probably worth someone else r-runing this as nobody has touched these files for, a while, and changing without tests makes me nervous!

Refs: #609 - account for new required field

---

CRM/Volunteer/Upgrader.php

The ActivityType API3 method was removed from core (and was long deprecated).
Fixes #622

Fix installation on CiviCRM 6.0 and later
